import "./globals.css";
import { Inter } from "next/font/google";
import { Passion_One } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const passionOne = Passion_One({ subsets: ["latin"], weight: ['400', '700', '900'] } );



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
